# Generated by Django 2.0.5 on 2018-05-23 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Filenames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='filename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triptech_web.Filenames'),
        ),
    ]
