# Generated by Django 2.0.5 on 2018-06-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptech_web', '0002_assignments_submissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='assignments',
            name='date_due',
            field=models.DateTimeField(default=models.DateTimeField(verbose_name='date'), verbose_name='due date'),
        ),
    ]
